---
title: Блог
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: Чтобы самому не забыть и другим рассказать
paginate: 10
paginate_path: page:num
highlighter: rouge
future: false
show_drafts: false
url: https://sergknyz.github.io/
shorturl: sergknyz
favicon: public/favicon.ico
author:
  name: Serg Knyz
  url: https://sergknyz.github.io/
pages_list:
  О блоге: "/about"
  Статьи: "/archive"
  Категории: "/tags"
  RSS-Лента: "/atom.xml"
gems:
- jemoji
- jekyll-paginate
- jekyll-gist
theme: jekyll-theme-slate
