---
title: Блог
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  test:
    title: test
    output: true
permalink: pretty
tagline: Информатизация музыкального служения
paginate: 10
paginate_path: page:num
highlighter: rouge
future: false
show_drafts: false
baseurl: sergknyz.github.io
shorturl: sergknyz
favicon: public/favicon.ico
author:
  name: Serg Knyz
  url: https://sergknyz.github.io
pages_list:
  Статьи: "/archive"
  Категории: "/categories"
  Тэги: "/tags"
  О блоге: "/about"
  RSS: "/atom.xml"
gems:
- jemoji
- jekyll-paginate
- jekyll-gist
- 
